### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by g4s8** [artipie/helm-adapter#100]
Scope of work for Helm adapter:
- [x]  `curl PUT` tgz archive with chart
- [x] `helm install` (there is no IT that verifies the work of this basic command)
- [ ] `helm repo index` (class `IndexByDirectory` was created but it is not included to our API)
- [ ] `helm repo index --merge` (class `IndexMergingSlice` was created but it is not included to our API)
- [ ] remove chart #106 
- [ ] reindex all packages in whole repo #105

**Comment by 0crat** [comment]
Job `gh:artipie/helm-adapter#100` is not assigned, can't get performer
