### ISSUE TITLE
Helm SDK methods

### ISSUE THREAD

**Issue by g4s8** [artipie/helm-adapter#109]
Let's add batch-update for Helm index file and provide SDK methods similar to RPM repository.
Also, we'll need an optional parameter to disable index update on single package upload.

Progress:
- [x] Reader of index file for obtaining versions about charts
- [x] add packages, `add(Collection<Key>)`
  - [x] implementation
  - [x] tests
- [x] remove packages, `remove(Collection<Key>)` 
  - [x] implementation
  - [x] tests

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#117](https://github.com/artipie/helm-adapter/issues/117) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#117](https://github.com/artipie/helm-adapter/issues/117), [#134](https://github.com/artipie/helm-adapter/issues/134) are still not solved.

**Comment by 0pdd** [comment]
@g4s8 all 2 puzzles are solved here: [#117](https://github.com/artipie/helm-adapter/issues/117), [#134](https://github.com/artipie/helm-adapter/issues/134).

**Comment by genryxy** [comment]
Close as `add` and `remove` were added

**Comment by g4s8** [comment]
@genryxy thanks
