### ISSUE TITLE
Helm - local repository

### ISSUE THREAD

**Issue by g4s8** [artipie/helm-adapter#110]
Scope of work for local repository:
- [x]  `curl PUT` tgz archive with chart
- [x] `helm install` (there is no IT that verifies the work of this basic command)  
- [x] remove chart #106 
- [x] reindex all packages in whole repo #105 
- [x] Helm SDK methods #109 

 ~~`helm repo index` (class `IndexByDirectory` was created but it is not included to our API)~~ (this command does not generate any request because it is local client command. So, it does not necessary to include this class to `HelmSlice`)  
 ~~`helm repo index --merge` (class `IndexMergingSlice` was created but it is not included to our API)~~ (this command does not generate any request because it is local client command. So, it does not necessary to include this class to `HelmSlice`)

**Comment by g4s8** [comment]
@genryxy could you please link here all tickets related to local registry?

**Comment by genryxy** [comment]
@g4s8 I added to the scope one ticket about batch update of index file

**Comment by genryxy** [comment]
@g4s8 all issues from this ticket are solved now. It could be closed

**Comment by g4s8** [comment]
@genryxy thanks

**Comment by genryxy** [comment]
@g4s8 could you please release a new version

**Comment by g4s8** [comment]
@genryxy done: https://github.com/artipie/helm-adapter/issues/174
