### ISSUE TITLE
PushChartSlice.java:63-65: Implement PushChart endpoint...

### ISSUE THREAD

**Issue by 0pdd** [artipie/helm-adapter#15]
The puzzle `13-d5c3ea9d` from #13 has to be resolved: 

https://github.com/artipie/helm-adapter/blob/72543e9971a445546af4ab497a698067591808cf/src/main/java/com/artipie/helm/PushChartSlice.java#L63-L65

The puzzle was created by @Sammers21 on 22-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) I'm not managing this repo, remove the [webhook](https://github.com/artipie/helm-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/helm-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0pdd** [comment]
The puzzle `13-d5c3ea9d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/helm-adapter#15` is not assigned, can't get performer
