### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by genryxy** [artipie/helm-adapter#194]
Performance of three main operations of Helm SDK API has decreased after in version `1.0.1`. It is necessary to investigate this problem, to find some bottlenecks and eliminate them. VisualVM could be used for profiling and sampling

**Comment by g4s8** [comment]
@genryxy you may want to check streaming YAML parser by Jackson: https://github.com/FasterXML/jackson-dataformats-text/tree/master/yaml

**Comment by genryxy** [comment]
Performance was improved according to this [table](https://github.com/artipie/helm-adapter/tree/master/benchmarks/results). And version [`v.1.1.1`](https://github.com/artipie/helm-adapter/releases/tag/v1.1.1) was released
