### ISSUE TITLE
initial setup + docs

### ISSUE THREAD

**Issue by Guseyn** [artipie/helm-adapter#2]

**Comment by 0crat** [comment]
@guseyn[/z](https://www.0crat.com/u/guseyn) I'm not managing this repo, remove the [webhook](https://github.com/artipie/helm-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/helm-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/helm-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
