### ISSUE TITLE
TgzArchive.java:64-66: TgzArchive name method For now...

### ISSUE THREAD

**Issue by 0pdd** [artipie/helm-adapter#20]
The puzzle `12-e4bf7d8b` from #12 has to be resolved: 

https://github.com/artipie/helm-adapter/blob/d2172aad58a34357706baef1b1c56b5550c58356/src/main/java/com/artipie/helm/TgzArchive.java#L64-L66

The puzzle was created by @Sammers21 on 27-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#20](https://github.com/artipie/helm-adapter/issues/20) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f8f7d0ea-0a84-4410-b1b8-5f951bd90ad4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `12-e4bf7d8b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 29 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by sereshqua** [comment]
@0crat quality good
