### ISSUE TITLE
TgzArchive.java:76-78: Save the archive into Asto. For...

### ISSUE THREAD

**Issue by 0pdd** [artipie/helm-adapter#21]
The puzzle `12-328a6b37` from #12 has to be resolved: 

https://github.com/artipie/helm-adapter/blob/d2172aad58a34357706baef1b1c56b5550c58356/src/main/java/com/artipie/helm/TgzArchive.java#L76-L78

The puzzle was created by @Sammers21 on 27-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#21](https://github.com/artipie/helm-adapter/issues/21) assigned to @sammers21[/z](https://www.0crat.com/u/sammers21), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/3550b695-db44-4f6b-8150-83510bbd6f58); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @sammers21[/z](https://www.0crat.com/u/sammers21) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; we should be aware that @sammers21[/z](https://www.0crat.com/u/sammers21) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `12-328a6b37` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#26](https://github.com/artipie/helm-adapter/issues/26) is still not solved.

**Comment by 0crat** [comment]
Job [#21](https://github.com/artipie/helm-adapter/issues/21) is not in the agenda of @sammers21[/z](https://www.0crat.com/u/sammers21), can't set title

**Comment by 0crat** [comment]
Job [#21](https://github.com/artipie/helm-adapter/issues/21) is not in the agenda of @sammers21[/z](https://www.0crat.com/u/sammers21), can't set title

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @sammers21[/z](https://www.0crat.com/u/sammers21), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#26](https://github.com/artipie/helm-adapter/issues/26) is solved here.
