### ISSUE TITLE
TgzArchive.java:142-144: Reimplement with slices Instead...

### ISSUE THREAD

**Issue by 0pdd** [artipie/helm-adapter#26]
The puzzle `21-a79af815` from #21 has to be resolved: 

https://github.com/artipie/helm-adapter/blob/b4282778d322610be567cc40fec3bfb084ce9a75/src/main/java/com/artipie/helm/TgzArchive.java#L142-L144

The puzzle was created by @Sammers21 on 01-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `21-a79af815` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/helm-adapter#26` is not assigned, can't get performer
