### ISSUE TITLE
TarArchiveTest.java:62-64: Replace FileStorage with...

### ISSUE THREAD

**Issue by 0pdd** [artipie/helm-adapter#29]
The puzzle `19-c97efbaf` from #19 has to be resolved: 

https://github.com/artipie/helm-adapter/blob/d2f3b0bf342a951fa6242dffc68ca9d45d158653/src/test/java/com/artipie/helm/TarArchiveTest.java#L62-L64

The puzzle was created by @Sammers21 on 04-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue
