### ISSUE TITLE
IndexYaml.java:112-114: Implement IndexYaml#empty For now...

### ISSUE THREAD

**Issue by 0pdd** [artipie/helm-adapter#31]
The puzzle `89-bbfe0d9a` from #89 has to be resolved: 

https://github.com/artipie/helm-adapter/blob/be7abd13eba286fe18fbf997f8f06ddd6c0ac79c/src/main/java/com/artipie/helm/IndexYaml.java#L112-L114

The puzzle was created by @Sammers21 on 08-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `89-bbfe0d9a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/helm-adapter#31` is not assigned, can't get performer
