### ISSUE TITLE
IndexYaml.java:124-127: Implement IndexYaml#empty This...

### ISSUE THREAD

**Issue by 0pdd** [artipie/helm-adapter#32]
The puzzle `89-cdf59b8a` from #89 has to be resolved: 

https://github.com/artipie/helm-adapter/blob/be7abd13eba286fe18fbf997f8f06ddd6c0ac79c/src/main/java/com/artipie/helm/IndexYaml.java#L124-L127

The puzzle was created by @Sammers21 on 08-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `89-cdf59b8a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#40](https://github.com/artipie/helm-adapter/issues/40), [#41](https://github.com/artipie/helm-adapter/issues/41), [#42](https://github.com/artipie/helm-adapter/issues/42), [#43](https://github.com/artipie/helm-adapter/issues/43) are still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/helm-adapter#32` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#41](https://github.com/artipie/helm-adapter/issues/41), [#42](https://github.com/artipie/helm-adapter/issues/42), [#43](https://github.com/artipie/helm-adapter/issues/43) are still not solved; solved: [#40](https://github.com/artipie/helm-adapter/issues/40).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#41](https://github.com/artipie/helm-adapter/issues/41), [#43](https://github.com/artipie/helm-adapter/issues/43) are still not solved; solved: [#40](https://github.com/artipie/helm-adapter/issues/40), [#42](https://github.com/artipie/helm-adapter/issues/42).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#43](https://github.com/artipie/helm-adapter/issues/43) is still not solved; solved: [#40](https://github.com/artipie/helm-adapter/issues/40), [#41](https://github.com/artipie/helm-adapter/issues/41), [#42](https://github.com/artipie/helm-adapter/issues/42).

**Comment by 0pdd** [comment]
@0pdd all 4 puzzles are solved here: [#40](https://github.com/artipie/helm-adapter/issues/40), [#41](https://github.com/artipie/helm-adapter/issues/41), [#42](https://github.com/artipie/helm-adapter/issues/42), [#43](https://github.com/artipie/helm-adapter/issues/43).
