### ISSUE TITLE
IndexYaml.java:155-157: Create a unit test for urls field...

### ISSUE THREAD

**Issue by 0pdd** [artipie/helm-adapter#43]
The puzzle `32-3ab761f4` from #32 has to be resolved: 

https://github.com/artipie/helm-adapter/blob/1aa237505bc1952d4a2c8fc9c579db750cfb5dec/src/main/java/com/artipie/helm/IndexYaml.java#L155-L157

The puzzle was created by @Sammers21 on 15-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `32-3ab761f4` has disappeared from the source code, that's why I closed this issue.
