### ISSUE TITLE
SubmitChartITCase.java:83-85: Ensure that the generated...

### ISSUE THREAD

**Issue by 0pdd** [artipie/helm-adapter#52]
The puzzle `1-f8ff3e8f` from #1 has to be resolved: 

https://github.com/artipie/helm-adapter/blob/a552f76d4aa1a2fd8e987558cae100b06f793901/src/test/java/com/artipie/helm/SubmitChartITCase.java#L83-L85

The puzzle was created by @Sammers21 on 29-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `1-f8ff3e8f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/helm-adapter#52` is not assigned, can't get performer
