### ISSUE TITLE
SubmitChartITCase.java:114-117: Bind reference repo to a...

### ISSUE THREAD

**Issue by 0pdd** [artipie/helm-adapter#53]
The puzzle `44-c6205a1b` from #44 has to be resolved: 

https://github.com/artipie/helm-adapter/blob/2ad995274d55d25ba1e8085681190d7fb7ecf4ba/src/test/java/com/artipie/helm/SubmitChartITCase.java#L114-L117

The puzzle was created by @Sammers21 on 01-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `44-c6205a1b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:artipie/helm-adapter#53` is not assigned, can't get performer
