### ISSUE TITLE
Use another library for yaml

### ISSUE THREAD

**Issue by genryxy** [artipie/helm-adapter#74]
Let's use `eo-yaml` instead of `snakeyaml` library for processing of `yaml` files as `eo-yaml` is used in all other repositories.
Also, add tests to make sure that the yaml update files does not corrupt the content.

The main task is to rework the method for updating the `index.yaml`. The following cases should be considered:
 * `entries` section isn't represented  in the `index.yaml`
 * `entries` section is represented, but node for chart name doesn't exist
 *  `entries` section and node for chart name are represented, but node for chart doesn't have a required version
 *  `entries` section and node for chart name are represented. Also node for chart contains a required version

**Comment by Sammers21** [comment]
> Let's use `eo-yaml` instead of `snakeyaml` library for processing of `yaml` files as `eo-yaml` is used in all other repositories.

Reasonable, but when the project was started, `eo-yaml` formatting was broken, that is why `snakeyaml` was used. Are not it's still broken?

> Also, add tests to make sure that the yaml update files does not corrupt the content.
> 
> The main task is to rework the method for updating the `index.yaml`. The following cases should be considered:
> 
> * `entries` section isn't represented  in the `index.yaml`

If it would be true, helm commands would fail; so it's false.

> * `entries` section is represented, but node for chart name doesn't exist

What is `node for chart name`?

> * `entries` section and node for chart name are represented, but node for chart doesn't have a required version

Looks like this statement contradicts to the previous one.

> * `entries` section and node for chart name are represented. Also node for chart contains a required version

Overall, it is a very strange issue description.

**Comment by genryxy** [comment]
@Sammers21 thanks for your comments. I missed the point that not all arrays have double indents in the `chart.yaml`. So, I need to revert these changes.
> entries section isn't represented in the `index.yaml`  

It's possible case, when we only create `index.yaml`. At first, we use empty yaml.
`node for chart name` is a name from the `chart.yaml` file

> Looks like this statement contradicts to the previous one.  
It doesn't contradict to the previous one because chart can have several versions. And version for the chart can be represented or absent in the `index.yaml`.

**Comment by genryxy** [comment]
`eo-yaml` could not parse `index.yaml` due to the lack of indents  for array elements. So, this issue could be closed.

**Comment by 0crat** [comment]
Job `gh:artipie/helm-adapter#74` is not assigned, can't get performer
