### ISSUE TITLE
Index.yml file generation

### ISSUE THREAD

**Issue by Sammers21** [artipie/helm-adapter#8]
According to [the official documentation](https://helm.sh/docs/topics/chart_repository/#the-index-file), `index.yml` is the primary metadata file in a chart repo, which contains all the metadata information concerning a registry. 

This issue suggest implementing `index.yml` file generation.

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) I'm not managing this repo, remove the [webhook](https://github.com/artipie/helm-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/helm-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@Sammers21 
>This Pull Request suggest implementing index.yml file generation.

It's not a pull request actually. Is it a kind of subtask for #1 ticket?

**Comment by Sammers21** [comment]
@g4s8,Yes

**Comment by 0crat** [comment]
I'm not managing `artipie/helm-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@Sammers21 the puzzle [#18](https://github.com/artipie/helm-adapter/issues/18) is still not solved.

**Comment by 0pdd** [comment]
@Sammers21 the only puzzle [#18](https://github.com/artipie/helm-adapter/issues/18) is solved here.

**Comment by 0crat** [comment]
Job `gh:artipie/helm-adapter#8` is not assigned, can't get performer
