### ISSUE TITLE
Helm integration tests failing

### ISSUE THREAD

**Issue by genryxy** [artipie/helm-adapter#81]
`HelmCompatibilityITCase#helmRepoAddAndUpdateWorks` test started to fail because of the following error:
```
STDERR:
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
```
The problem is related to the fact that https://kubernetes-charts.storage.googleapis.com/index.yaml as default stable repository is no longer allowed (https://stackoverflow.com/a/65404574/14676855). It is necessary to fix this problem.

**Comment by 0crat** [comment]
Job `gh:artipie/helm-adapter#81` is not assigned, can't get performer
