### ISSUE TITLE
Delete specified chart from index.yaml file

### ISSUE THREAD

**Issue by genryxy** [artipie/helm-adapter#84]
It is necessary to support deleting of specified chart from `index.yaml` file within `IndexYaml` class. The methods `deleteByName` and `deleteByNameAndVersion` should be implemented and tested.

**Comment by 0pdd** [comment]
@genryxy the puzzle [#86](https://github.com/artipie/helm-adapter/issues/86) is still not solved.

**Comment by 0pdd** [comment]
@genryxy the only puzzle [#86](https://github.com/artipie/helm-adapter/issues/86) is solved here.

**Comment by 0crat** [comment]
Job `gh:artipie/helm-adapter#84` is not assigned, can't get performer
