### ISSUE TITLE
IndexYaml.java:134-136: Remove duplicating code. There is...

### ISSUE THREAD

**Issue by 0pdd** [artipie/helm-adapter#86]
The puzzle `84-6dc281f6` from #84 has to be resolved: 

https://github.com/artipie/helm-adapter/blob/3089ea716935645e06f6c9de47b9fca1571707aa/src/main/java/com/artipie/helm/metadata/IndexYaml.java#L134-L136

The puzzle was created by Aleksandr Krasnov on 11-Jan-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job `gh:artipie/helm-adapter#86` is not assigned, can't get performer
