### ISSUE TITLE
Merging multiple `index.yaml` files

### ISSUE THREAD

**Issue by genryxy** [artipie/helm-adapter#89]
It is necessary to provide a method to merge multiple `index.yaml` files.
See: https://helm.sh/docs/helm/helm_repo_index/ (with flag `--merge`)
Part of #83

**Comment by 0crat** [comment]
You @genryxy[/z](https://www.0crat.com/u/genryxy) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:artipie/helm-adapter#89` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@genryxy all 6 puzzles are solved here: [#31](https://github.com/artipie/helm-adapter/issues/31), [#32](https://github.com/artipie/helm-adapter/issues/32), [#40](https://github.com/artipie/helm-adapter/issues/40), [#41](https://github.com/artipie/helm-adapter/issues/41), [#42](https://github.com/artipie/helm-adapter/issues/42), [#43](https://github.com/artipie/helm-adapter/issues/43).
