### ISSUE TITLE
Obtains `index.yaml` file based on the prefix

### ISSUE THREAD

**Issue by genryxy** [artipie/helm-adapter#90]
It is necessary to provide a method for obtaining `index.yaml` based on the prefix needs to be added.
See: https://helm.sh/docs/helm/helm_repo_index/
Part of #83

**Comment by 0crat** [comment]
You @genryxy[/z](https://www.0crat.com/u/genryxy) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0pdd** [comment]
@genryxy the puzzle [#94](https://github.com/artipie/helm-adapter/issues/94) is still not solved.

**Comment by 0crat** [comment]
Job `gh:artipie/helm-adapter#90` is not assigned, can't get performer

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.2`

**Comment by 0pdd** [comment]
@genryxy the puzzle [#108](https://github.com/artipie/helm-adapter/issues/108) is still not solved; solved: [#94](https://github.com/artipie/helm-adapter/issues/94).
