### ISSUE TITLE
IndexByDirectory.java:107-111: Extract logic for creating...

### ISSUE THREAD

**Issue by 0pdd** [artipie/helm-adapter#94]
The puzzle `90-d6ead5a4` from #90 has to be resolved: 

https://github.com/artipie/helm-adapter/blob/efe607f499cf124ad163a0a77b24eff5f15efd18/src/main/java/com/artipie/helm/metadata/IndexByDirectory.java#L107-L111

The puzzle was created by Aleksandr Krasnov on 21-Jan-21. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `90-d6ead5a4` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#108](https://github.com/artipie/helm-adapter/issues/108) is still not solved.

**Comment by 0crat** [comment]
Job [#94](https://github.com/artipie/helm-adapter/issues/94) is not in the agenda of @andreoss[/z](https://www.0crat.com/u/andreoss), can't set title
